# Generated by Django 5.2.1 on 2025-05-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
